### ISSUE TITLE
serial::Write implementation is blocking

### ISSUE THREAD

**Issue by Nemo157** [therealprof/nrf51-hal#4]
Opening this issue to avoid polluting https://github.com/japaric/nb/issues/13 with too much device specific discussion.

---

The current `impl embedded_hal::serial::Write for Tx<UART0>` is blocking, the easy implementation of

```rust
fn write(&mut self, byte: u8) -> nb::Result<(), !> {
    let uart = unsafe { &*UART0::ptr() };
    if uart.events_txdrdy.read().bits() == 1 {
         uart.events_txdrdy.reset();
         uart.txd.write(|w| unsafe { w.bits(u32::from(byte)) });
         Ok(())
    } else {
        Err(nb::Error::WouldBlock)
    }
}
```

doesn't work because `events_txdrdy` is only set _after_ a byte is transmitted, not when the peripheral is first enabled. It doesn't appear to be possible to manually set event registers as well.

**Comment by therealprof** [comment]
Thanks for the ticket. I'll have a look.

**Comment by therealprof** [comment]
Turns out it was rather easy to address by just pumping in a \0 byte during initialisation even before enabling the UART.

**Comment by Nemo157** [comment]
I’m surprised that works, but happy to hear it :)
